[build]
  functions = "lambda"
  command = "make build"
  publish = "public"
[build.environment]
GO_IMPORT_PATH = "github.com/smithcoin/smithco.in"

[context.js]
  command = "make deploy-js"

[context.go]
  command = "make deploy-go"
